### ISSUE TITLE
Introduce ```opera info``` and ```opera set``` command

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#104]
The ```opera info``` command would print out the current initialization of the project. In other words, ```opera init``` prepares everything to deploy, while ```opera info``` would provide the printout of:

- root blueprint file
- csar location
- inputs file name/location
- (status) initialised/deployed/error

So if the ```opera init``` fails, the user would be able to manually set some things for non-standard CSARs.

@sstanovnik, can you please review this requirement?

**Comment by sstanovnik** [comment]
What would `opera set` be? A way to set these parameters? Not a good idea I think, this would be better suited for a csar authoring/publishing command. We have a PR or issue open for this I think.

Is the csar in "csar location" the extracted root? Technically incorrect, because csars are only compressed service archives. Maybe `content_root`?

Otherwise this seems fine. I'd just like to propose a schema so we don't have freeform output. My quasi-spec suggestion:

```json
{
    "entrypoint":             "string | null",
    "csar (or content_root)": "string",
    "inputs_file":            "string | null",
    "status":                 "oneof(initialised, deployed, error)"
}
```

If you want freeform as default, please also include `opera info [--format <text|json>]` so this is machine-parseable.

**Comment by cankarm** [comment]
With ```opera set``` was the idea to manually set init values for development. In this case you would be able to update init values, which are then retrieved by SaaS (with info command). This would allow retrieving data of the last execution.

**Comment by sstanovnik** [comment]
Info command added in #106, the decision about set postponed.
