### ISSUE TITLE
Using Opera-SaaS with curl commands

### ISSUE THREAD

**Issue by AlexSpart** [xlab-si/xopera-opera#148]
I am trying to replicate the example scenario of using Opera-SaaS with curl commands that can be found on the documentation (https://github.com/xlab-si/xopera-opera/blob/master/docs/saas.rst) but there seems to be a problem.

More detailed documentation on the procedure and the actual commands would be appreciated a lot.

You can find the logs here:
[opera-saas-curl-log.log](https://github.com/xlab-si/xopera-opera/files/5735788/opera-saas-curl-log.log)

**Comment by anzoman** [comment]
@sstanovnik can you take a look and provide some additional info here?

**Comment by sstanovnik** [comment]
It seems I've forgotten to update these commands to use RADON authentication. I have a WIP in https://github.com/xlab-si/xopera-opera/tree/saas-auth-curls, but I can't verify it works yet because RADON's auth server currently doesn't. 

I'll update this when I verify it works, but you can try out the changes yourself if the auth server becomes available before I get a chance to verify.

**Comment by AlexSpart** [comment]
Hi @sstanovnik , I want to inform you that CHE is up and running again, so please give an update when possible

**Comment by sstanovnik** [comment]
I've tested my changes and they work. When #160 is merged, the docs will be updated with the instructions.
