### ISSUE TITLE
Access to secondary implementation artifacts with xOpera

### ISSUE THREAD

**Issue by abitrolly** [xlab-si/xopera-opera#247]
I tried to deploy real app source with `opera` binary and standard Ansible playbook, and it looks like xOpera just doesn't support this.

All examples are creating files from embedded content in YAML file. Ansible notebook can not see local files, because xOpera copies notebook into `/tmp` before executing, but doesn't copy referenced files.

**Comment by anzoman** [comment]
@abitrolly yes `opera` works in a temporary folder when running executors (e.g., Ansible playbooks) and prints out the results back to storage folder (`.opera` by default). This is okay because TOSCA allows defining and using all the necessary files that accompany the executors - you can do this within TOSCA interfaces and operations (see 3.6.16 Operation implementation definition) using `dependencies` keyname.

**Comment by abitrolly** [comment]
Can you give an example? Given a `.zip` file in a directory with `service.yaml`. How to make that file available for a playbook?

**Comment by anzoman** [comment]
Sure, I am listing some of the examples from [xopera-examples](https://github.com/xlab-si/xopera-examples) repository:

- https://github.com/xlab-si/xopera-examples/blob/master/tosca/relationship-outputs/service.yaml#L84
- https://github.com/xlab-si/xopera-examples/blob/master/csars/misc-tosca-types/modules/node_types/hello/hello.yaml#L31
- https://github.com/xlab-si/xopera-examples/blob/master/cloud/platform-connection/aws-azure-connection/aws-azure/modules/aws/aws_role/aws_role.yaml#L35
- https://github.com/xlab-si/xopera-examples/blob/master/cloud/azure/thumbnail-generator/modules/function-deploy/function-deploy.yaml#L60

**Comment by anzoman** [comment]
@abitrolly just checking - have you managed to look at the examples above and were they of any use to you?

**Comment by anzoman** [comment]
I believe this has been resolved and we can always reopen if there are still any questions.
