### ISSUE TITLE
Use case: Deploy a service template on a third-party platform

### ISSUE THREAD

**Issue by matejart** [xlab-si/xopera-opera#39]
Use case: Deploy a service template on a third-party platform
=============================================================

## Description

This use case covers a workflow of installing a [TOSCA library](https://github.com/xlab-si/xopera-opera/issues/41#issuecomment-630784044) for a third-party platform of choice, then using it in a service template to successfully run a deploy.

## Prerequisites

* A TOSCA library named `vendor.platform` exists and is available.
* A tool for managing TOSCA libraries exists and is installed in the actor's working environment. Let's call the tool `overture`.
* `opera` is installed in the actor's working environment.
* User's `$PWD` is in the root folder of their service template in a valid [CSAR-based structure](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cs01/TOSCA-Simple-Profile-YAML-v1.3-cs01.html#_Toc20821079).

## Steps

* User installs the TOSCA library `vendor.platform`:

      $ overture install vendor.platform

* User authors a service template:

      $ cd ~/project/demo-034
      $ ls
      inputs.yaml service.yaml
      $ head -n 4 service.yaml
      tosca_definitions_version: tosca_simple_yaml_1_3

      imports:
        - /library/vendor/platform/main.yaml

* User creates a CSAR of the project:

      $ overture package --output demo-034.csar .

* User initializes the deployment environment for the service:

      $ opera init --inputs inputs.yaml demo-034.csar

* User runs the deploy of the service:

      $ opera deploy

## Expected results

* The TOSCA library `vendor.platform` is globally available for current and any subsequent deployments.
* The `demo-034.csar` is a TOSCA-compliant CSAR containing the service template and copies of any type definitions and imported implementations.
* An instance of the service as described in the service template is deployed.

**Comment by anzoman** [comment]
Hi, according to this proposal implementing this with xOpera would mean that we will probably have to add some new features. Those thing could be:

- add `opera init` command 
- add `opera package` command
- add support for compressed CSARs and arhives (this enhancement is already present here: #27)   with `--template` option to tell opera which file in CSAR is the actual service template that will be executed
- refactor `opera deploy` command to start the deployment that was initialized in the deployment environment by the user

Does this sound reasonable?

**Comment by matejart** [comment]
@anzoman yes, that's the implication. But first, let us see any issues or unforeseen implications of the use case itself.

**Comment by dradX** [comment]
@matejart , @anzoman 

Please take this comment as a suggestion on making the planned `opera` CLI more understandable and atomic with regards to subcommand use and deployment environment. I understand I might be a bit late on this suggestion but nevertheless it could give us another prospective. 

I see the intent on using the TOSCA Library on multiple services and it is a great idea - this is exactly what TOSCA is about _reusability_ and it should be implemented. 

From the perspective of the orchestrator, however, having another tool (we call it `overture` in the original issue definition) for adding the TOSCA Library(ies) to be used and referenced by the orchestrator in another service template might be an overkill, since this can surely be done in a separate `opera` subcommand, avoiding the need for a separate tool in the orchestrators toolset. 

Setting up the TOSCA Libraries could be done via this syntax: 

```opera import vendor.platform```

or even giving it simply a path to the TOSCA Libray definition:

``` opera import ../library/example```

The `opera import` subcommand should check the _validity_ of the imported TOSCA Library - something opera will have to do eaither way, thus resolving the need to cover this process by a separate tool.

I also appreciate the initiative to provide a subcommand for packaging a service template in CSAR (Cloud Service Archive) and I see its potential beyond the service/TOSCA Library packaging use case. Instead of using `opera package` I would suggest using `opera pack` syntax instead like done in [git](https://git-scm.com/docs) for example.
Usually it is a good practice defining the subcommands as _imperative words_, as already done with `opera deploy` or `opera undeploy`. This usually gives the user a clear understanding of the semantics using subcommands vs arguments.
For creating the CSAR this syntax might be easier for the user to understand: 

```opera pack ./path/to/demo -o ./demo.csar```

If the path to the service template isn't structured corresponding to the 6. TOSCA CSAR definition (single YAML file in `./path/to/demo` or `TOSCA.Meta` file in the specified TOSCA-Metadata directory) opera returns an error:

`Could't create demo.csar: invalid TOSCA CSAR file structure in ./path/to/demo`

Having the `opera pack` implemented an orthogonal `opera unpack` subcommand might be used to unpack the CSAR into a specific directory using this syntax:

```opera unpack demo.csar ./path/to/unpacked/demo```

From this point on the workflow for deploying stays the same as usual. 
The _inputs_ file provide inputs for the deploy/undeploy workflow so these are needed only at deployment/undeployment time which means that inputs should be considered within `opera deploy` or `opera undeploy` subcommands. Providing the inputs in a Just-In-Time manner adds consistency to the overall CLI design. 

For deployment of the service template with inputs:

`opera deploy -i inputs.yaml ./path/to/unpacked/demo/main.yaml`

For undeployment of the service template with inputs:

`opera undeploy -i inputs.yaml ./path/to/unpacked/demo/main.yaml`

**Comment by anzoman** [comment]
@dradX thank you for the suggestions. 

I agree that we should be careful when introducing the TOSCA library and that the simple usage of the opera orchestrator should remain forever. 

The `opera pack` command name you proposed seems acceptable but to me `opera package` seems to be in harmony with TOSCA as TOSCA profile in YAML v1.3 talks about a package artifact:

> TOSCA archive (or TOSCA Cloud Service Archive, or “CSAR”): a package artifact that contains a TOSCA service template and other artifacts usable by a TOSCA orchestrator to deploy an application.

The command for the unpacking also is reasonable. And yes `inputs.yaml` are not the part of the CSAR and they should be considered just for the deployment/undeployment part.

**Comment by dradX** [comment]
@anzoman Thank you for the answer, but in the answer you are relating to "a package"  as _noun_ eg. a product, while it would be nice to use `pack` as a _imperative verb_ for commands.

**Comment by anzoman** [comment]
@dradX well yes certainly pack this is an option, so let us see what @matejart thinks about this. Eventually, if we will pick either pack or package I expect that both to be seen as verbs.

**Comment by matejart** [comment]
Thank you, @dradX , for your thoughts and the detailed proposal. It gives a useful perspective to me.

But I think that we shouldn't be afraid of introducing new tools. It is better to have multiple simple and well-defined tools instead of one that does everything. `opera` is an orchestrator and its subcommands need to have to do with the service template deployments. It should expect the input in a valid form and act upon it. The how it gets built, what repository it was sourced from, how the user populates the library and other things like that should not be the concern of the _orchestrator_. That's a task of a _packager_ or a _library manager_ or any other similar tool.

This discussion has also got me thinking that `opera package` doesn't belong in this group, so I should change the use case text. What got me at the time of building the concept was the fact that it needs to parse the service template to do its work. But the parser is a library, so it can be easily used in another tool. Plus, it was easier to make. But I did have the [verb](https://www.oxfordlearnersdictionaries.com/definition/american_english/package_2) in mind, I didn't even think that it could be interpreted as a noun in the context. And pack is also a [noun](https://www.oxfordlearnersdictionaries.com/definition/english/pack_2), so I'm not sure we win either way. 

Further, `opera import` doesn't sound quite right to me. Importing is something you do from within the TOSCA templates. Instead, this action is more in the line of installing a library. Think `pip install`.

And having to use `opera unpack` also feels unnecessary, because what the orchestrator has to do with its input is an implementation detail that should be completely transparent to the user.

For these reasons, I am not in favour of going into this direction.

**Comment by matejart** [comment]
Changes to the use case description:

* added a prerequisite about the structure of the user's service template,
* moved the function of packaging to the proposed tool `overture`,
* removed the `--template` switch from the `opera init` line, because the access point definitions template is defied in the CSAR structure.

**Comment by anzoman** [comment]
This issue has been inactive for almost a year now and TOSCA service templates and CSARs can now be deployed easily with opera. We can reopen this issue if we need in the future.
