### ISSUE TITLE
Add `deploy -f <>` option

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#46]
## Description
Opera saves the deployment process output and therefore it can resume deploy procedure which was not successful or it ended prematurely. In some cases the DevOps engineer would prefer to re-run everything from the start and not skipping successful Ansible script executions. The limits or potential problems of this procedure are described in NOTE section below.

## Prerequisites
- `opera` installed
- project, e.g. `service.yaml` 

## Steps

- User starts deploy, which is interrupted

```
$ opera deploy service.yaml 
  Deploying first node
     Executing create on the_first_ansible_role
  Deploying second node
Interrupt !!!

```
- continue without force:

```
$ opera deploy service.yaml 
  Deploying second node
    Executing create on the_second_ansible_role
```

- **continue with force**
 ```
$ opera deploy -f service.yaml 
  Deploying first node
     Executing create on the_first_ansible_role
  Deploying second node
    Executing create on the_second_ansible_role
```

## Expected results
- continue with force should re-run all steps and Ansible playbooks.

## NOTE
This action should be available only if application blueprint did not changed its structure, otherwise some deployed nodes from previous deployment would become un-managed by xOpera, and would be impossible to undeploy/clean them if they are not described in a _new_ blueprint. For a start I would suggest to allow this force command only if blueprint did not change at all.

If user creates significant changes in blueprint, user should clean previous deployment, e. g.:
  ```
$ opera deploy -f service.yaml 
   Error: The service.yaml blueprint structure has changed. You should run "opera undeploy" first to clean and re-deploy service, or use unchanged blueprint. 
```

**Comment by matejart** [comment]
Thank you, @cankarm , for this proposal. I see the need behind this request, but I don't feel that this is the right approach.

* In my opinion, the opera's behaviour that it resumes deploy where it left off from the previous deploy is a lucky mistake. Ansible doesn't do that, so opera, at this point shouldn't either.
* Given that, I'd argue that the _normal_ behaviour should be the one you propose for the `-f` in the text before NOTE. So I'd say: no switch means start over. Or, if the user puts a `--resume` switch, do what opera does now, on the user's own responsibility.
* `deploy` means initial deploy. It is not a redeploy, it is not an update or change, so there should be no expectation of computing any differences between previous deploys and the current one. I believe that new commands would be needed for that. 
* If the developer wants a clean stepback, then calling `opera undeploy` is the best option. Forcing a new deploy from the start should always create a new service instance. Once you start that, you throw away any state of previous deploys. So checking for differences when using `--force`, then having opera refuse the force does not make sense.
* #40

**Comment by cankarm** [comment]
Oh... that's even better @matejart!  I like the `--resume` approach, because it implicates that _blueprint has not changed_. Everything in my _NOTE_ comment is there just because I was afraid to add functionality that users would exploit for things that it was not created.

So, I will wait for a bit, and if I get a few _thumbsups_ here, I'll close this issue and create the `--resume` one, and link the discussion here.

**Comment by matejart** [comment]
With `--resume`, I would still emit a warning that the results may not be the same as when a full clean deploy is done, but I am much more comfortable with this approach.

**Comment by dradX** [comment]
This is indeed a very reasonable solution for the changed xOprea behaviour regarding the execution of the deploy command. At this point I would agree with @matejart view and implement `deploy` as “no questions asked” deployment of the blueprint from the start and adding the possibility for the user to use `—resume` in the case of errors/abortion of the previous deployment process.

**Comment by anzoman** [comment]
@matejart thanks for your explanation. I've observed other orchestrators (e.g. Yistia Yorc, Indigo DC, Puccini, Cloudify) and the vast majority of them also treat each deployment separately and when deploy is called this means that everything starts over and goes through the whole process defined in the TOSCA service template. So I see `opera deploy --resume` command option as a good upcoming feature. But to be completely sure this is the right way - what do you think @tadeboro?

**Comment by matejart** [comment]
@anzoman yes, that is one source of inspiration. On the other hand, terraform seems to be quite happy to get a changed blueprint in the second deployment, and threats it as an update of an existing deployment. But as I stated before, TOSCA treats `deploy` as a one-time deal, and anything else needs to be handled in a different workflow. Giving the user an option to `--resume` is a good compromise where we say, that this is not really normal, but if the user insists, then fine.

**Comment by matejart** [comment]
By the way, and I may be deeply into the territory of music requests, I was thinking about the following behaviour:

* If you run `opera deploy ...` on the already deployed instance, you get an error, telling you that the deploy is already done or partially done.
* You can then run `opera deploy --resume ...`, get a warning, but the deploy resumes.
* Or, you can do `opera deploy --force` which deletes the previous instance model and starts fresh.

**Comment by cankarm** [comment]
Hehe, this is really a music request, covering all options.

**Comment by dradX** [comment]
@matejart I have to admit I am more in favor of your previous comment leaving the user the possibility to use:
- a) to use `opera --resume` if he/she wants to continue deployment from where it stopped last time (nice feature) which implies the users knowledge about the possible changes made to the blueprint operation implementation steps.

- b) `opera deploy` to always execute deployment operation steps from start regardless of what has been or not/deployed possibly issuing a warning stating `The deploy operation might have unexpected consequences on the already existing deployed blueprint`. 

I feel that adding an error in `opera deploy` when a blueprint has already been deployed or partially deployed and forcing the user to use `opera deploy --force` would be like putting roadblocks on the users path for a blueprint deployment.  
I also note that there is/(shouldn't be) nothing stopping the users issuing `opera deploy --force` also for initial deployment thus adding ambiguity, since this should be the "standard - deploy from start" way to use `opera deploy`. 

BTW: To be completely clear I absolutly agree that a redeploy of a changed blueprint deserves another command, as you suggested in the first comment.

**Comment by anzoman** [comment]
@dradX that's a good point. I agree that I would be better to treat every invoked deployment separately. 

I believe that it is important to keep things as simple as possible (but not simpler) so that opera orchestrator would be easy to install (like it is now) and easy to use without to many things to be done before user can start the deployment. And that `opera redeploy` suggestion could be useful and maybe redeploy could work in a way that it would run undeploy first and after that deploy. But I also think that it is important to discuss if this redeploy is worth implementing or would it be just another command that would complicate things rather than simplifying them.

**Comment by matejart** [comment]
@dradX you are right, the idea _was_ to put a roadblock upon the second `opera deploy`. I'd like the tool to stop me if it finds that I'm trying something outside the happy path.

`opera deploy --force` from the start should be ok, because the switch just means "make sure any prevous deployment isn't there". The standard `opera deploy` from the start, however, should assume that the workspace is clean. If it finds that it isn't clean, there should be a roadblock.

@anzoman When I suggested another command, I actually had in mind a separate workflow in TOSCA. But now that I think of it, I was considering this several months ago: the orchestrator can figure out a difference between the current instance model and the incoming one. For any of the removed or changed nodes, it could issue parts of the Standard and Configure interfaces (e.g., it removes a node with `delete` and does `remove_source` and `remove_target` as needed, then do the usual `deploy` stuff). But this is just in thoughts so far.

**Comment by dradX** [comment]
@matejart Thank you for the explanation and I agree that the suggested implementation leaves the users selecting any reasonable possibility of using `opera deploy`.

@anzoman I think the `opera redeploy` or `opera reconfigure` should be implemented and it comes extremely handy in a scenario with a great number of nodes deployed and only several of them need to be reconfigured (undeployed/reconfigured/redeployed) - without the need to call `opera undeploy` of the current deployment and then subsequently `opera deploy` of the changed deployment blueprint.

@matejart Thank you for giving us a good insight of the possible implementation of this scenario. A currently deployed blueprint (OLD) and the modified blueprint (CHANGED) should be present at redeployment time for this to work properly - so having a changed internal workflow (not the sole reason) probably calls for the need of implementation of a separate `opera` command.
