### ISSUE TITLE
node_templates section defined in imported service templates

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#49]
## Description
In some cases, it would be useful to import a service template that already contains some node_templates defined. For example, in a situation, when a service template describing existing infastruture that cannot be modified externally (e.g. HPC nodes) is automatically generated by some service and later imported into other templates.  
## Prerequisites
- `opera` installed
- A valid TOSCA Service Template file `service.yaml` that contains an import definition of another valid TOSCA Service Template file with **topology_template** and **node_templates** sections defined.
## Steps
- User runs deploy `opera deploy service.yaml`
## Current behaviour
- xOpera returns an error `Duplicate keys 'node_templates' found in service.yml`
## Expected behavior
- Service template is deployed without error.

**Comment by anzoman** [comment]
Thanks for bringing this up. I see that sometimes it could be useful to import another `node_templates` section but as you look closer this could be a problem and I don't think that you wanna split your deployment declarations.

Within TOSCA imports which is an optional key one declares a list of import statements that are pointing to external YAML documents with TOSCA definitions. These documents usually contain reusable TOSCA type definitions (like Node Types, Relationship Types, Artifact Types, etc.) and here for instance Node Type is reusable entity but Node Templates are not.

According to TOSCA standard (section 3.1.3.1 which is called Additional Requirements) node_templates, relationship_templates, inputs, outputs are all duplicate template names so you can define them only once in your service template otherwise an error should be raised. So in this case  it is right that xOpera returns duplicate keys error.

Could it be possible that you somehow just parse your immutable HPC service template and then join the parsed node_templates with your mutable service template TOSCA document?

**Comment by alexmaslenn** [comment]
> According to TOSCA standard (section 3.1.3.1 which is called Additional Requirements) node_templates, relationship_templates, inputs, outputs are all duplicate template names so you can define them only once in your service template otherwise an error should be raised. So in this case it is right that xOpera returns duplicate keys error.
> 
Not sure that this is entirely true. In my opinion section 3.1.3.1 merely states that node template names shall be unique across the whole Service Template  
>Duplicate Template names within a Service Template’s Topology Template SHALL be considered an error.  These include, but are not limited to duplicate names found for the following template types:
o    Node Templates (node_templates)
o    Relationship Templates (relationship_templates)
o    Inputs (inputs)
o    Outputs (outputs)
>

**Comment by matejart** [comment]
@alexmaslenn thank you for this use case. May I ask you to expand on it with the context of the actual use of the change? I know you mention it in the description, but to give us a better picture, try and move that to the steps. E.g., I assume you run some tool which generates one yaml, then you edit the service.yaml to import that first yaml, etc.?

**Comment by matejart** [comment]
Here are my comments so far though. I looked at the 3.6.8 Import definition:

> _An import definition is used within a TOSCA Service Template to locate and uniquely name another TOSCA Service Template file which has type and template definitions to be imported (included) and referenced within another Service Template._

From this definition, and along with what was already cited in our conversation, I honestly cannot decide if merging node and relationship templates is fine or not across the service templates or not. The wording of "_imported (included)_" is particularly jarring, because including other service templates in my service template would make my template as if I copied and pasted those contents into mine. And thus I shouldn't repeat those keywords that are not duplicate. Importing, on the other hand, to me suggests a more logical construction of the final result.

So if we go with the logical merging, what happens to duplicate node templates? Which one wins? I can't find this in the spec.

**Comment by alexmaslenn** [comment]
> May I ask you to expand on it with the context of the actual use of the change? I know you mention it in the description, but to give us a better picture, try and move that to the steps.

@matejart here is more detalied description:
- A dedicated tool generates TOSCA yaml file describing existing infrastructure. I may contain node types, capability types, relationship types along with node templates.
- This file is referenced in `imports` section of the service template that is going to be deployed
- Node template names from generated file can be used in requirement assigments in the deployed service template

The scenario above can be applied to muliple service templates across one project that target same infrastructure.

**Comment by alexmaslenn** [comment]
> So if we go with the logical merging, what happens to duplicate node templates? Which one wins? I can't find this in the spec.

@matejart I think the same logic should be applied, as it is done for **node_types** section for example. If we have duplicate node template names, no one wins, it is an error.
