### ISSUE TITLE
Enable tab completion for opera CLI arguments

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#56]
## Description
xOpera orchestrator uses [`argparse`](https://pypi.org/project/argparse/) Python library for parsing the command line arguments. This package encapsulates the option to use help for opera's commands and its subcommands which is good for the users. But apart from that it would be even better to be able to use tab completion for all of those commands and arguments as this is commonly used within prominent, prosperous and modern console clients. Thus I suggest to use [`argcomplete`](https://pypi.org/project/argcomplete/) Python package in order to implement the behaviour for optional tab-completion for the CLI.

## Steps

To implement this we would probably need to:

- use the`argcomplete` pip package and add it to `setup.cfg` and `Pipfile`
- import the package within the `xopera-opera/src/opera/cli.py` file and use it for the main parser and for the subparsers
- maybe we'll need to use the argcomplete package in the other Python files in `xopera-opera/src/opera/commands`

## Current behaviour
Currently xOpera does not offer tab completion for any of the commands or argument options. 

## Expected results
To be able to perform tab completion for the opera's commands, subcommands and argument CLI options.

**Comment by matejart** [comment]
Thank you for this suggestion, @anzoman , as a user, I would certainly welcome this feature.

**Comment by anzoman** [comment]
@tadeboro and @matejart do you have some suggestion on how to realize this? I have tried to import  [`argparse`](https://pypi.org/project/argparse/), have run `activate-global-python-argcomplete` and have changed the contents in `src/opera/cli.py` like this:

```python
def create_parser():
    parser = ArgParser(
        description="opera orchestrator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    subparsers = parser.add_subparsers()
    # added this line
    argcomplete.autocomplete(parser)
    cmds = inspect.getmembers(commands, inspect.ismodule)
    for _, module in sorted(cmds, key=lambda x: x[0]):
        module.add_parser(subparsers)
    return parser
```

But this was not working. I think than we might need to include some script that will do `activate-global-python-argcomplete` or `eval "$(register-python-argcomplete my-awesome-script)"` Maybe we will also need to use `argcomplete.autocomplete(parser)` within all the subparsers.

**Comment by anzoman** [comment]
@sstanovnik I think that your magical skills can also help here. I just wanted to ask if you have any suggestion. Should we use `argcomplete`, `.pythonrc`, `.bashrc` or something else?

**Comment by sstanovnik** [comment]
Just as an alternative, I found https://github.com/iterative/shtab. That doesn't mean I compared the two, just that more than one exists, if you find something wrong with `argcomplete`.

Regarding usage, it's complicated. We first need to start with manual activation with

```shell
eval "$(opera shell-completion)"
```

which is really the only reliable way. It still doesn't take into account that more than one shell type exists: bash, the POSIX shell, fish, zsh, ash, csh, ksh, tcsh and more. They all (some are similar though) have different ways of setting completion, and some may not even support it. I'd suggest supporting whatever `argcomplete supports`, but with a mandatory parameter:

```shell
eval "$(opera shell-completion -s/--shell <bash|fish|zsh|csh>)"
```

leaving any possible autodetection for later.

The next step _would_ be installation, but this is really complicated and not worth the effort right now, imo, so let's not. Just for posterity, here are the problems.

First, who would you install this for? There are three options: somehow installing in a venv (is this possible and what happens with system-wide packages), installing for a user, and installing system-wide. Having `opera shell-completion --install` would help, but you then face the second problem: _how_ to install this. Systems have different settings for sourcing `bashrc` and what have you, and this also differs by shell. Supporting this matrix is difficult. Then what happens when you do some of this automatically and it causes launching the shell to fail? Many issues, and I think this is just the tip of the proverbial iceberg.

I hope this helped :)
