### ISSUE TITLE
Deployment of extracted CSAR fails with `Type is missing derived_from key`

### ISSUE THREAD

**Issue by duelle** [xlab-si/xopera-opera#79]
Version: `opera 0.5.8`

When trying to deploy the CSAR [sut.zip](https://github.com/xlab-si/xopera-opera/files/4970662/sut.zip) after extraction (`opera deploy _definitions/radonblueprints__SockShopTestingExample.tosca`), it fails with
```
% opera deploy _definitions/radonblueprints__SockShopTestingExample.tosca 
_definitions/radonpoliciestesting__Test.tosca:5:5: [PolicyType] Type is missing derived_from key.
```
We did not alter the Test policy type, so that's the way it was exported.

**Comment by anzoman** [comment]
Hi @duelle,

the error occurs because opera expects (and demands) that you use `derived_from` keyname within your entity defintions (e.g., Node Type, Relationship Type, Artifact Type, Policy Type definitions etc.). So I think that your problem could be solved if you add the line `derived_from: tosca.policies.Root` to the Policy Type defintion in `_definitions/radonpoliciestesting__Test.tosca`.

**Comment by duelle** [comment]
Thanks for the immediate reply.
As we didn't write this by hand but exported it from GMT, is this an issue in GMT that this isn't (or wasn't) included in the export to CSAR? Do you happen to know whether this is included in the latest version of GMT?

**Comment by anzoman** [comment]
Yes this may be an issue. I remember that all the nodes and relationships within the CSARs that were exported from the GMT had  `derived_from` keyname included in their definitions. I'm not sure whether this problem is concerning TOSCA policies only but it seems so. On the other hand, looking into [TOSCA standard](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969448) `derived_from` keyname (which is an optional parent Entity Type name the Entity Type derives from) is not marked as required - @matejart - do you know something about this? Should we refactor this part of opera so that `derived_from` will not be required and when user would not set it the policy/node/relationship would just derive from the root TOSCA type definition?

**Comment by anzoman** [comment]
@duelle is this issue still relevant and present?

**Comment by anzoman** [comment]
I believe that this was resolved and can be now closed.
